common/models/TypePost.php
<?php
namespace common\models;
use Yii;
use yii\db\ActiveRecord;
use yii\db\Query;
use common\models\Common;
use common\models\TypePost;
use yii\behaviors\SluggableBehavior;
class TypePost extends ActiveRecord 
{
    public static function tableName()
    {
        return '{{%type_post}}';
    }
    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::className(),
                'attribute' => 'title', // cột để phân tách thành slug
                'slugAttribute' => 'title_url', // cột lưu slug
            ],
        ];
    }
    /**
    * Thay đổi vị trí của bài viết
    * [BACKEND INDEX] [DRAG-DROP] [JQUERY]
    **/
    public static function changePosition($position) {
        $connection = Yii::$app->db;
        foreach($position as $p) {
            $index = $p[0];
            $newPosition = $p[1];
            $connection->createCommand()
            ->update('type_post', ['positions' => $newPosition], ['id' => $index])
            ->execute();
        }
    }
    /* 
    * Thay đổi checkbox khi nhấn button
    * [BACKEND INDEX] [TOGGLE CHECKBOX] [JQUERY]
    */
    public static function changeStatus($id,$status) {
        $connection = Yii::$app->db;
        $change = $connection->createCommand()
        ->update('type_post', ['status' => $status], ['id' => $id])
        ->execute();
        if($change) {
            return true;
        }
        else {
            return false;
        }
    }
    /**
    * Kiểm tra trùng title 
    * [BACKEND ADD-UPDATE] 
    * [CONTROLLER PRODUCT] [ADD - UPDATE]
    **/
    public static function checkUniqueName($title,$id = null) {
        $result = (new Query)
            ->select('p.title')
            ->from('type_post p')
            ->where(['p.title' => $title])
            ->andWhere(['<>','p.id' , $id])
            ->one();
        return $result;
    }
    /**
    * Danh sách tất cả loại post
    * [BACKEND INDEX] 
    **/
    public static function getAllTypePost() {
        $result = (new Query)
            ->select('id,name,description,image,status,short_description,positions')
            ->from(static::tableName())
            ->orderBy('positions desc,id desc')
            ->all();
        return $result;
    }
     public static function updateTypePost($dataForm) {
        if(!empty($dataForm['id'])){
            // nếu là update product
            $model = TypePost::findOne($dataForm['id']);
        }
        else{
            // nếu là thêm mới product
            $model = new TypePost();
            $model->time_create = time();
            $model->email = Yii::$app->user->identity->username;
            $model->positions = TypePost::find()->max('id') + 1;
        }
        $model->title = ! empty($dataForm['title']) ? $dataForm['title'] : "" ;
        $model->name = ! empty($dataForm['name']) ? $dataForm['name'] : "" ;
        $model->description = ! empty($dataForm['description']) ? $dataForm['description'] : "" ;
        $model->short_description = ! empty($dataForm['short_description']) ? $dataForm['short_description'] : "" ;
        $model->time_create = time();
        $model->status = !empty($dataForm['status']) ? 1 : 0 ;
        if(! empty($dataForm['image'])){
            $model->image = $dataForm['image'];
        }
        return $model->save();  
    }
    public static function deleteTypePost($id){
        $model =TypePost::findOne($id);
        return $model->delete();
    }
    /**
    * Danh sách loại post
    * [FRONTEND INDEX] 
    **/
    public static function getAllTypePostStatus() {
        $result = (new Query)
            ->select('id,name,description,image,status,short_description,title_url')
            ->from(static::tableName())
            ->where(['status' => 1])
            ->orderBy('positions desc,id desc')
            ->all();
        return $result;
    }
    /**
    * Tất cả bài viết thuộc loại bài viết
    * [FRONTEND TYPE-POST] 
    **/
    public static function getPostFollowTypePost($id) {
        $result = (new Query)
            ->select('p.title_url,p.id,p.name,p.description,p.short_description,p.image,p.id_type_post,tp.id as tp_id,tp.name as tp_name,tp.title_url as `tp_title_url`')
            ->from('post p')
            ->leftJoin('type_post tp', 'p.id_type_post = tp.id')
            ->where(['p.status' => '1','tp.title_url' => $id])
            ->orderBy('p.positions desc,p.id desc')
            ->all();
        return $result;
    }
}

backend/controllers/TypePostController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use common\models\forms\TypePostForm;
use common\models\TypePost;

/**
 * TypeProduct controller
 */
class TypePostController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                   
                    [
                        'actions' => [ 'index','add-type-post','update-type-post','delete-type-post','change-status','change-position'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            
        ];
    }
    /**
     * {@inheritdoc}
     */
    public $enableCsrfValidation = false; // use method post
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    /**
     * render dữ liệu vào View [Index]
     */
    public function actionIndex(){
        $allData = TypePost::getAllTypePost(); 
        return $this->render('index',
            [
                'allData' => $allData,
            ]
            
        );
    }
    /**
     * render dữ liệu vào View [addSlider]
     */

    public function actionAddTypePost(){
        Yii::$app->view->title = "Thêm loại bài viết";
       
        $model = new TypePostForm();
        $model->id = 0;
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->image = UploadedFile::getInstance($model, 'image');
            $dataForm = Yii::$app->request->post()['TypePostForm'];
            
            if(! empty($model->image->name)) { // nếu upload hình ảnh thành công
                $link = $model->upload(); // lưu vào path
                if($link){ // nếu có link trả về
                    $dataForm['image'] = $link; // gán biến dataForm logo vào Form
                }        

            }
            if(empty($dataForm['nameEN'])) {
                $dataForm['nameEN'] = $dataForm['nameVI'];
            }
            // Kiểm tra nếu description tiếng anh không có thì sẽ lấy tiếng việt
            if(empty($dataForm['contentEN'])) {
                $dataForm['contentEN'] = $dataForm['contentVI'] ;
            }
            // Kiểm tra nếu short_description tiếng anh không có thì sẽ lấy tiếng việt
            if(empty($dataForm['contentshortEN'])) {
                $dataForm['contentshortEN'] = $dataForm['contentshortVI'];
            }
            // $dataForm
            $dataForm['title'] = $dataForm['nameVI'];  
            $dataForm['name'] = json_encode(array('vi' => $dataForm['nameVI'],'en' => $dataForm['nameEN'])) ;
            $dataForm['description'] = json_encode(array('vi' => $dataForm['contentVI'],'en' => $dataForm['contentEN'])) ;
            $dataForm['short_description'] = json_encode(array('vi' => $dataForm['contentshortVI'],'en' => $dataForm['contentshortEN'])) ;
            
            $saveSetting = TypePost::updateTypePost($dataForm); // save form
            if($saveSetting) { // nếu save setting thành công  
                Yii::$app->session->setFlash('success', "Thêm thành công");
                return $this->redirect(['/type-post']);
            }
            else {
                Yii::$app->session->setFlash('error', "Thêm không thành công");
                return $this->redirect(['/type-post']);
            }  
        }       
        return $this->render('addTypePost',
            [
                'model' => $model,
                // 'position' => $position,
            ]
        );
    }
    /**
     * render dữ liệu vào View [updateTypePost]
     */
    public function actionUpdateTypePost(){
        Yii::$app->view->title = "Update loại bài viết";

        $id = Yii::$app->request->get('id'); // lấy dữ liệu từ URL
        $model = new TypePostForm();
        $data = TypePost::findOne($id); // Lấy dữ liệu từ db theo Id

        if($data){ // Nếu có dữ liệu
            $model->id = $id;
            if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            }
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                $model->image = UploadedFile::getInstance($model, 'image');
                $dataForm = Yii::$app->request->post()['TypePostForm'];
                
                if(! empty($model->image->name)) { // nếu upload hình ảnh thành công
                    $link = $model->upload(); // lưu vào path
                    if($link){ // nếu có link trả về
                        $dataForm['image'] = $link; // gán biến dataForm logo vào Form
                    }        

                }
                if(empty($dataForm['nameEN'])) {
                    $dataForm['nameEN'] = $dataForm['nameVI'];
                }
                // Kiểm tra nếu description tiếng anh không có thì sẽ lấy tiếng việt
                if(empty($dataForm['contentEN'])) {
                    $dataForm['contentEN'] = $dataForm['contentVI'] ;
                }
                // Kiểm tra nếu short_description tiếng anh không có thì sẽ lấy tiếng việt
                if(empty($dataForm['contentshortEN'])) {
                    $dataForm['contentshortEN'] = $dataForm['contentshortVI'];
                }
                // $dataForm
                $dataForm['title'] = $dataForm['nameVI'];  
                $dataForm['name'] = json_encode(array('vi' => $dataForm['nameVI'],'en' => $dataForm['nameEN'])) ;
                $dataForm['description'] = json_encode(array('vi' => $dataForm['contentVI'],'en' => $dataForm['contentEN'])) ;
                $dataForm['short_description'] = json_encode(array('vi' => $dataForm['contentshortVI'],'en' => $dataForm['contentshortEN'])) ;
                
                $saveSetting = TypePost::updateTypePost($dataForm); // save form
                if($saveSetting) { // nếu save setting thành công  
                    Yii::$app->session->setFlash('success', "Update thành công");
                    return $this->redirect(['/type-post/update-type-post' ,'id' => $id]);
                }
                else {
                    Yii::$app->session->setFlash('error', "Update không thành công");
                    return $this->redirect(['/type-post/update-type-post','id' => $id]);
                }  
            }    
            return $this->render('updateTypePost',
                [
                    'model' => $model,
                    'data' => $data,
                ]
            );
        }
        else { // Nếu không có dữ liệu
            return $this->redirect(['/type-post']);
        }
        
    }
    public function actionDeleteTypePost() {
        $id = Yii::$app->request->get('id');
        $delete = TypePost::deleteTypePost($id);
        return $this->redirect(['/type-post']);
    }
    public function actionChangeStatus() {
        $id = Yii::$app->request->get('id');
        $value = Yii::$app->request->get('value');
        $change = TypePost::changeStatus($id,$value);
        if($change) {
            return true;
        } 
        else {
            return false;
        }
    }
    public function actionChangePosition() {
        $positions = Yii::$app->request->get('positions');
        $change = TypePost::changePosition($positions);
        return true;
    }
   
}
   

frontend/controllers/TypePostController.php
<?php
namespace frontend\controllers;
use Yii;
use yii\web\Controller;
// use yii\web\UploadedFile;
// use common\models\forms\PostForm;
use common\models\TypePost;
use common\models\Post;
use yii\data\Pagination;
// use common\models\TypePost;
// use yii\helpers\ArrayHelper;
// use yii\filters\AccessControl;
// use yii\filters\VerbFilter;
/**
 * Post controller
 */
class TypePostController extends Controller
{
    public $enableCsrfValidation = false; // use method post
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    public function init() {
        parent::init();
    }
    public function actionTypePost() {
        // $query = Article::find()->where(['status' => 1]);
        // get the total number of articles (but do not fetch the article data yet)$id = $id = Yii::$app->request->get('id');
        $id = Yii::$app->request->get('id');
        $data = TypePost::getPostFollowTypePost($id);
        $count = count($data);
        // create a pagination object with the total count
        $pagination = new Pagination(['totalCount' => $count]);
        // print_r($pagination);
        // die();
        // // limit the query using the pagination and retrieve the articles
        // // $articles = $query->offset($pagination->4)
        // //     ->limit($pagination->limit)
        // //     ->all();
        // //     print_r($articles);
        // // $data = TypeProduct::getPostId($id);
        return $this->render('type_post',
            [
                'data' => $data,
                'pagination' => $pagination,
            ]
        );
    }
    public function actionIndex() {
        // $query = Article::find()->where(['status' => 1]);
        // get the total number of articles (but do not fetch the article data yet)$id = $id = Yii::$app->request->get('id');
        // $id = Yii::$app->request->get('id');
        $data = Post::getPost();
        $count = count($data);
        // create a pagination object with the total count
        $pagination = new Pagination(['totalCount' => $count]);
        // print_r($pagination);
        // die();
        // // limit the query using the pagination and retrieve the articles
        // // $articles = $query->offset($pagination->4)
        // //     ->limit($pagination->limit)
        // //     ->all();
        // //     print_r($articles);
        // // $data = TypeProduct::getPostId($id);
        return $this->render('index',
            [
                'data' => $data,
                'pagination' => $pagination,
            ]
        );
    }
}

backend/views/type-post/addTypePost.php
<?php

use yii\helpers\Url;

use yii\bootstrap\ActiveForm;

use yii\helpers\Html;

?>

<style>

	.has-error .help-block-error{

		transition:height 0.3s ease-out; 

		height: 15px;

		font-style: italic;

    	font-weight: bold;

		  

	}

	.help-block-error{		 

		 height:0px;

		 transition:height 0.3s ease-out;

	}

	input {

		border:1px solid !important;

	}

	label {

    	font-weight: 400;

    	color: black;

	}

	.form-control:focus{

		border:2px solid !important;

		border-color: #3c8dbc !important;

    	box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075), 0 0 8px rgba(102, 175, 233, 0.6);

	}

	.box-body{

		padding:25px;

	}

	.hidden{

		transition: 0.5s;

	}

	.show{

		transition: 0.5s;

	}

</style>



<div class="box box-primary">



	<?php  echo Yii::$app->controller->renderPartial('/layouts/breadcum')  ?>

	<div class="row">

		<div class="col-md-12">

		 	<?php if (Yii::$app->session->hasFlash('success')): ?>

			    <div class="alert alert-success alert-dismissable"> 

			        <i class="icon fa fa-check"></i><?= Yii::$app->session->getFlash('success') ?>

			    </div>

			<?php endif; ?> 

			<?php if (Yii::$app->session->hasFlash('error')): ?>

			    <div class="alert alert-error alert-dismissable"> 

			        <?= Yii::$app->session->getFlash('error') ?>

			    </div>

			<?php endif; ?> 

		</div>

	</div>

	<div class="row">

		<div class="col-md-12">

    		<?php $form = ActiveForm::begin(

			[

				'id' => 'form-add-product',

				'options' => [

			        'enctype' => 'multipart/form-data'

			    ]

         

			]);?>

			<div class="box-body">

		  		<div class="form-group row">

		  			

		  			<label for="name" class="col-sm-2 col-form-label">

						<div>Tên (*)</div>

						<a class="btn btn-info change" style="margin-top: 10px">Thay đổi ngôn ngữ</a>

					</label>

					

					

					<div class="col-sm-8">

							<div class="title_vi">

								<?= $form->field($model, 'nameVI')->textInput(['autofocus' => true])->label('Ngôn ngữ tiếng việt') ?>

							</div>

							<div class="title_en">

								<?= $form->field($model, 'nameEN')->textInput(['autofocus' => true])->label('Ngôn ngữ tiếng anh') ?>

							</div>

						  

						  	

						</div>

					

		  		</div>

		  		<div class="form-group row">

		  			

			  			<label class="col-sm-2 col-form-label">

							<div>Mô tả </div>

						</label>

						<div class="col-sm-8">

							<div class="content_footer_vi">

						  	<?= $form->field($model, 'contentVI')->textarea([

						  		'rows' => '12',

						  		'id' => 'content_footer_vi'

						  		

						  	])->label('Ngôn ngữ tiếng việt') ?>

						  	</div>

						  	<div class="content_footer_en">

						  	<?= $form->field($model, 'contentEN')->textarea([

						  		'rows' => '12',

						  		'id' => 'content_footer_en'

						  		

						  	])->label('Ngôn ngữ tiếng anh') ?>

						  	</div>

						</div>

						<!-- <div class="col-sm-8 content_footer_en" style="display: none"> -->

							

						  	

						<!-- </div> -->

			  		

		  		</div>
		  		<div class="form-group row">

		  			

			  			<label class="col-sm-2 col-form-label">

							<div>Mô tả ngắn</div>

						</label>

						<div class="col-sm-8">

							<div class="content_footer_vi">

						  	<?= $form->field($model, 'contentshortVI')->textInput([

						  		'rows' => '12',

						  		'id' => 'content_footer_vi'

						  		

						  	])->label('Ngôn ngữ tiếng việt') ?>

						  	</div>

						  	<div class="content_footer_en">

						  	<?= $form->field($model, 'contentshortEN')->textInput([

						  		'rows' => '12',

						  		'id' => 'content_footer_en'

						  		

						  	])->label('Ngôn ngữ tiếng anh') ?>

						  	</div>

						</div>

						<!-- <div class="col-sm-8 content_footer_en" style="display: none"> -->

							

						  	

						<!-- </div> -->

			  		

		  		</div>

				

		  		

		  		<div class="form-group row">

		  			<label class="col-sm-2 col-form-label">

						Hình Ảnh

					</label>

					<div class="col-sm-10">

  						<?= $form->field($model, 'image')->fileInput(['class' => 'image', 'accept'=>".png,.jpg" ])->label(false) ?>

					  	<div class="display_image">

					  		<img src="" width=200px>

					  	</div>

					</div>

				</div>

				

				

				<div class="form-group row">

					<label  class="col-sm-2 control-label">

						Status

					</label>



					<div class="col-sm-10">

					  	<?= $form

                        ->field($model, 'status')

                        ->checkbox([

                        	"data-toggle" => "toggle", 

                        	"data-size"=>"sm",

                        	"checked"=>"checked"

                        

                        ])->label(false)?>

					</div>



				</div>

		  		<div class="form-group row">

		  			<div class="col-sm-2"></div>

			  		<div class="col-sm-2">

					 	<button type="submit" class="btn btn-info ">Cập Nhật</button>

					</div>

			  	</div>

	 		</div>

			<?php ActiveForm::end(); ?>

		</div>

		

	</div>

	

</div>

backend/views/type-post/index.php
<?php
use yii\helpers\Url;
?>
<style>
  ul{padding-left:0px;}
  .padding{
    padding:10px;
  }
</style>
<section class="content">
  <div class="row">
      <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
               <a class="btn btn-success" href="<?php echo Url::to(['/type-post/add-type-post']);  ?>">
                  <i class="fa fa-plus"></i> Thêm mới
               </a>
            </div>
            <div class="box-body">
                <table id="slider_backend" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                          <th>STT</th>
                          <th>Tên</th>
                          <!-- <th>Description</th> -->
                          <th>Image</th>
                          <th>Status</th>                          
                          <th>Sửa</th>                          
                          <th>Xóa</th>                          
                        </tr>
                    </thead>
                    <tbody id="sortable">
                        <?php
                        $stt = 1; 
                        foreach ($allData as $ad) : ?>
                           <tr class="ui-state-default ui-sortable-handle" data-position="<?php echo $ad['positions'] ?> " data-id="<?php echo $ad['id'] ?>" data-url="type-post/change-position">
                              <input type="hidden" name="id" value="<?php echo $ad['id'] ?>">
                              <td><?php echo $stt ++ ?></td>
                              <td style="text-align: left;padding:0px">
                                
                                  <div class="padding"><?php echo !empty(json_decode($ad['name'])->vi) ? json_decode($ad['name'])->vi : "" ?></div>
                                 
                              </td>
                             
                              <td style="width:20%">
                                 <?php if($ad['image'] == "") : ?>
                                    <div></div>
                                 <?php else : ?>   
                                    <img src="<?php echo Url::to('../'.$ad['image']); ?>" width=100px height=100px>
                                 <?php endif ?>
                              </td>
                              <td>
                              <?php if($ad['status'] == 1): ?>
                                 <input data-url="type-post/change-status" data-value="<?php echo $ad['id']  ?>" name="status" class="status change-status" type="checkbox" checked data-toggle="toggle" data-size="sm" >
                              <?php else : ?>
                                 <input data-url="type-post/change-status" data-value="<?php echo $ad['id'] ?>" name="status" class="status change-status" type="checkbox" data-toggle="toggle" data-size="sm">
                              <?php endif ?>
                              </td>
                              <td class="text-center">
                                <a href="<?php echo Url::to(['/type-post/update-type-post', 'id' => $ad['id']]);  ?>"><i class="glyphicon glyphicon-edit"></i></a>
                              </td>
                              <td class="text-center">
                                <a href="<?php echo Url::to(['/type-post/delete-type-post', 'id' => $ad['id']]);  ?>"> <i class="fa fa-remove"></i></a>
                              </td>
                           </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
  </div>
</section>

backend/views/type-post/updateTypePost.php
<?php

use yii\helpers\Url;

use yii\bootstrap\ActiveForm;

use yii\helpers\Html;

?>

<style>

	.has-error .help-block-error{

		transition:height 0.3s ease-out; 

		height: 15px;

		font-style: italic;

    	font-weight: bold;

		  

	}

	.help-block-error{		 

		 height:0px;

		 transition:height 0.3s ease-out;

	}

	input {

		border:1px solid !important;

	}

	label {

    	font-weight: 400;

    	color: black;

	}

	.form-control:focus{

		border:2px solid !important;

		border-color: #3c8dbc !important;

    	box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075), 0 0 8px rgba(102, 175, 233, 0.6);

	}

	.box-body{

		padding:25px;

	}

	.hidden{

		transition: 0.5s;

	}

	.show{

		transition: 0.5s;

	}

</style>



<div class="box box-primary">



	<?php  echo Yii::$app->controller->renderPartial('/layouts/breadcum')  ?>

	<div class="row">

		<div class="col-md-12">

		 	<?php if (Yii::$app->session->hasFlash('success')): ?>

			    <div class="alert alert-success alert-dismissable"> 

			        <i class="icon fa fa-check"></i><?= Yii::$app->session->getFlash('success') ?>

			    </div>

			<?php endif; ?> 

			<?php if (Yii::$app->session->hasFlash('error')): ?>

			    <div class="alert alert-error alert-dismissable"> 

			        <?= Yii::$app->session->getFlash('error') ?>

			    </div>

			<?php endif; ?> 

		</div>

	</div>

	<div class="row">

		<div class="col-md-12">

    		<?php $form = ActiveForm::begin(

			[

				'id' => 'form-add-product',

				'options' => [

			        'enctype' => 'multipart/form-data'

			    ]

         

			]);?>

			<div class="box-body">

		  		<div class="form-group row">

		  			<?= $form->field($model, 'id')->hiddenInput(['value'=>$data['id']])->label(false); ?>

		  			<label for="name" class="col-sm-2 col-form-label">

						<div>Tên (*)</div>

						<a class="btn btn-info change" style="margin-top: 10px">Thay đổi ngôn ngữ</a>

					</label>

					

					

					<div class="col-sm-8">

							<div class="title_vi">

								<?= $form->field($model, 'nameVI')->textInput([

									'autofocus' => true,

									'value' =>  !empty(json_decode($data['name'])->vi) ? json_decode($data['name'])->vi : " "

								])->label('Ngôn ngữ tiếng việt') ?>

							</div>

							<div class="title_en">

								<?= $form->field($model, 'nameEN')->textInput([

									'autofocus' => true,

									'value' => !empty(json_decode($data['name'])->en) ? json_decode($data['name'])->en : " "

								])->label('Ngôn ngữ tiếng anh') ?>

							</div>

						  

						  	

						</div>

					

		  		</div>

		  		<div class="form-group row">

		  			

			  			<label class="col-sm-2 col-form-label">

							<div>Mô tả </div>

						</label>

						<div class="col-sm-8">

							<div class="content_footer_vi">

						  	<?= $form->field($model, 'contentVI')->textarea([

						  		'rows' => '12',

						  		'id' => 'content_footer_vi',

						  		'value' => !empty(json_decode($data['description'])->vi) ? json_decode($data['description'])->vi : " "

						  		

						  	])->label('Ngôn ngữ tiếng việt') ?>

						  	</div>

						  	<div class="content_footer_en">

						  	<?= $form->field($model, 'contentEN')->textarea([

						  		'rows' => '12',

						  		'id' => 'content_footer_en',

						  		'value' => !empty(json_decode($data['description'])->en) ? json_decode($data['description'])->en : " "

						  		

						  	])->label('Ngôn ngữ tiếng anh') ?>

						  	</div>

						</div>

						<!-- <div class="col-sm-8 content_footer_en" style="display: none"> -->

							

						  	

						<!-- </div> -->

			  		

		  		</div>

				<div class="form-group row">

		  			

		  			<label class="col-sm-2 col-form-label">

						<div>Mô tả ngắn</div>

					</label>

					<div class="col-sm-8">

						<div class="content_footer_vi">

					  	<?= $form->field($model, 'contentshortVI')->textInput([

					  		'rows' => '12',

					  		'id' => 'content_footer_vi',

					  		'value' => !empty(json_decode($data['short_description'])->vi) ? json_decode($data['short_description'])->vi : " "

					  		

					  	])->label('Ngôn ngữ tiếng việt') ?>

					  	</div>

					  	<div class="content_footer_en">

					  	<?= $form->field($model, 'contentshortEN')->textInput([

					  		'rows' => '12',

					  		'id' => 'content_footer_en',

					  		'value' => !empty(json_decode($data['short_description'])->en) ? json_decode($data['short_description'])->en : " "

					  		

					  	])->label('Ngôn ngữ tiếng anh') ?>

					  	</div>

					</div>

					<!-- <div class="col-sm-8 content_footer_en" style="display: none"> -->

						

					  	

					<!-- </div> -->

			  		

		  		</div>

		  		

		  		<div class="form-group row">

		  			<label class="col-sm-2 col-form-label">

						Hình Ảnh

					</label>

					<div class="col-sm-10">

  						<?= $form->field($model, 'image')->fileInput([

  							'class' => 'image',

  							'accept'=>".png,.jpg",

  							'value' => Url::to([$data['image']])

  						])->label(false) ?>

					  	<div class="display_image">

					  		<img src="<?php echo Url::to('../../'.$data['image']); ?>" width=200px>

					  	</div>

					</div>

				</div>

				



				<div class="form-group row">

					<label  class="col-sm-2 control-label">

						Status

					</label>



					<div class="col-sm-10">

					  	<?= $form

                        ->field($model, 'status')

                        ->checkbox([

                        	"data-toggle" => "toggle", 

                        	"data-size"=>"sm",

                        	"checked"=>"checked"

                        

                        ])->label(false)?>

					</div>



				</div>

		  		<div class="form-group row">

		  			<div class="col-sm-2"></div>

			  		<div class="col-sm-2">

					 	<button type="submit" class="btn btn-info ">Cập Nhật</button>

					</div>

			  	</div>

	 		</div>

			<?php ActiveForm::end(); ?>

		</div>

		

	</div>

	

</div>