common/models/Slider.php
<?php
namespace common\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Query;
use common\models\Common;

/**
 * Slider model
 *
 * @property integer $id
 * @property string $title
 * @property string $description    
 * @property string $image
 * @property string $status
 */
class Slider extends ActiveRecord 
{
  
    public static function tableName()
    {
        return '{{%slider}}';
    }
    /**
     * Lấy tất cả sliderr trong db
     * @return array [thông tin slider]
     */
    public static function getAllSlider(){
        $result = (new Query)
                ->select('id,name,description,image,status,positions')
                ->from(static::tableName())
                ->orderBy('positions desc,id desc')
                ->all();
        return $result;
    }
    /**
    * Thay đổi vị trí của bài viết
    * [BACKEND INDEX] [DRAG-DROP] [JQUERY]
    **/
    public static function changePosition($position) {
        $connection = Yii::$app->db;
        foreach($position as $p) {
            $index = $p[0];
            $newPosition = $p[1];
            $connection->createCommand()
            ->update('slider', ['positions' => $newPosition], ['id' => $index])
            ->execute();
        }
    }
    /**
    * Hiển thị hay không hiển thị bài
    **/
    public static function changeStatus($id,$status) {
        $connection = Yii::$app->db;
        $change = $connection->createCommand()
        ->update(static::tableName(), ['status' => $status], ['id' => $id])
        ->execute();
        if($change) {
            return true;
        }
        else {
            return false;
        }
    }
    /**
     * Lưu form slider
     * @param $dataForm [dữ liệu từ form slider gửi lên server]
     */
    public static function updateSlider($dataForm) {
        if(!empty($dataForm['id'])){
            // nếu là update slider
            $model = Slider::findOne($dataForm['id']);
        }
        else{
            // nếu là thêm mới slider
            $model = new Slider();
            $model->positions = Slider::find()->max('id') + 1;
        }
        
        $model->name = ! empty($dataForm['name']) ? $dataForm['name'] : "" ;
        $model->description = ! empty($dataForm['description']) ? $dataForm['description'] : "" ;
        $model->link = ! empty($dataForm['link']) ? $dataForm['link'] : "" ;
        $model->status = !empty($dataForm['status']) ? 1 : 0 ;
      
        if(! empty($dataForm['image'])){
            $model->image = $dataForm['image'];
        }
        return $model->save();  
    }
    public static function deleteSlider($id){
        $model =Slider::findOne($id);
        return $model->delete();
    }
    
    /* 
    * Lấy tất cả slider đang hoạt động 
    * [FRONTEND] [SLIDER INDEX]
    */
    public static function getSlider(){
        $result = (new Query)
                ->select('image,link')
                ->from(static::tableName())
                ->where(['status' => 1])
                ->orderBy('positions desc,id desc')
                ->all();
        return $result;
    }
   


}

backend/controllers/SliderController.php
<?php
namespace backend\controllers;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\Slider;
use yii\web\UploadedFile;
use common\models\forms\SliderForm;
/**
 * Slider controller
 */
class SliderController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [ 'index','add-slider','update-slider','delete-slider','change-status','change-position'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }
    /**
     * {@inheritdoc}
     */
    public $enableCsrfValidation = false; // use method post
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    /**
     * render dữ liệu vào View [Index]
     */
    public function actionIndex(){
        Yii::$app->view->title = "Danh sách Slider";
        $allSlider = Slider::getAllSlider(); // lấy tất cả slider
        return $this->render('index',
            [
                'slider' => $allSlider,
            ]
        );
    }
    /**
     * render dữ liệu vào View [addSlider]
     */
    public function actionAddSlider(){
        Yii::$app->view->title = "Thêm Slider";
        $model = new SliderForm();
        if (Yii::$app->request->isPost) {
            $model->image = UploadedFile::getInstance($model, 'image');
            $dataForm = Yii::$app->request->post()['SliderForm'];
            if(! empty($model->image->name)) { // nếu upload hình ảnh thành công
                $link = $model->upload(); // lưu vào path
                if($link){ // nếu có link trả về
                    $dataForm['image'] = $link; // gán biến dataForm logo vào Form
                }        
            }
            // $dataForm
            $dataForm['name'] = json_encode(array('vi' => $dataForm['nameVI'],'en' => $dataForm['nameEN'])) ;
            $dataForm['description'] = json_encode(array('vi' => $dataForm['contentVI'],'en' => $dataForm['contentEN'])) ;
            $saveSetting = Slider::updateSlider($dataForm); // save form
            if($saveSetting) { // nếu save setting thành công  
                Yii::$app->session->setFlash('success', "Thêm thành công");
                return $this->redirect(['/slider']);
            }
            else {
                Yii::$app->session->setFlash('error', "Thêm không thành công");
                return $this->redirect(['/slider']);
            }  
        }     
        return $this->render('addSlider',
            [
                'model' => $model,
            ]
        );
    }
    /**
     * render dữ liệu vào View [updateSlider]
     */
    public function actionUpdateSlider(){
        Yii::$app->view->title = "Update Slider";
        $id = Yii::$app->request->get('id'); // lấy dữ liệu từ URL
        $model = new SliderForm();
        $data = Slider::findOne($id); // Lấy dữ liệu từ db theo Id
        if($data){ // Nếu có dữ liệu
            if (Yii::$app->request->isPost) {
                $model->image = UploadedFile::getInstance($model, 'image');
                $dataForm = Yii::$app->request->post()['SliderForm'];
                if(! empty($model->image->name)) { // nếu upload hình ảnh thành công
                    $link = $model->upload(); // lưu vào path
                    if($link){ // nếu có link trả về
                        $dataForm['image'] = $link; // gán biến dataForm logo vào Form
                    }        
                }
                // $dataForm
                $dataForm['name'] = json_encode(array('vi' => $dataForm['nameVI'],'en' => $dataForm['nameEN'])) ;
                $dataForm['description'] = json_encode(array('vi' => $dataForm['contentVI'],'en' => $dataForm['contentEN'])) ;
                $saveSetting = Slider::updateSlider($dataForm); // save form
                if($saveSetting) { // nếu save setting thành công  
                    Yii::$app->session->setFlash('success', "Update thành công");
                    return $this->redirect(['/slider/update-slider','id' => $id]);
                }
                else {
                    Yii::$app->session->setFlash('error', "Update không thành công");
                    return $this->redirect(['/slider/update-slider','id' => $id]);
                }  
            }    
            return $this->render('updateSlider',
                [
                    'model' => $model,
                    'data' => $data,
                ]
            );
        }
        else { // Nếu không có dữ liệu
            Yii::$app->session->setFlash('error', "Không có dữ liệu");
            return $this->redirect(['/slider']);
        }
    }
    public function actionDeleteSlider(){
        $id = Yii::$app->request->get('id');
        $delete = Slider::deleteSlider($id);
        return $this->redirect(['/slider']);
    }
    public function actionChangeStatus() {
        $id = Yii::$app->request->get('id');
        $value = Yii::$app->request->get('value');
        $change = Slider::changeStatus($id,$value);
        if($change) {
            return true;
        } 
        else {
            return false;
        }
        // return $this->redirect(['/product']);
    }
    public function actionChangePosition() {
        $positions = Yii::$app->request->get('positions');
        $change = Slider::changePosition($positions);
        return true;
    }
}

backend/views/slider/addSlider.php
<?php
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
?>
<div class="box box-primary">
	<?php  echo Yii::$app->controller->renderPartial('/layouts/breadcum')  ?>
	<div class="row">
		<div class="col-md-12">
		 	<?php if (Yii::$app->session->hasFlash('success')): ?>
			    <div class="alert alert-success alert-dismissable"> 
			        <i class="icon fa fa-check"></i><?= Yii::$app->session->getFlash('success') ?>
			    </div>
			<?php endif; ?> 
			<?php if (Yii::$app->session->hasFlash('error')): ?>
			    <div class="alert alert-error alert-dismissable"> 
			        <?= Yii::$app->session->getFlash('error') ?>
			    </div>
			<?php endif; ?> 
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
    		<?php $form = ActiveForm::begin(
			[
				'id' => 'form-add-product',
				'options' => [
			        'enctype' => 'multipart/form-data'
			    ]
			]);?>
			<div class="box-body">
		  		<div class="form-group row">
		  			<label for="name" class="col-sm-2 col-form-label">
						<div>Tên</div>
						<a class="btn btn-info change" style="margin-top: 10px">Thay đổi ngôn ngữ</a>
					</label>
					<div class="col-sm-8">
							<div class="title_vi">
								<?= $form->field($model, 'nameVI')->textInput(['autofocus' => true])->label('Ngôn ngữ tiếng việt') ?>
							</div>
							<div class="title_en">
								<?= $form->field($model, 'nameEN')->textInput(['autofocus' => true])->label('Ngôn ngữ tiếng anh') ?>
							</div>
						</div>
		  		</div>
		  		<div class="form-group row">
		  			<label for="name" class="col-sm-2 col-form-label">
						<div>Link</div>
					</label>
					<div class="col-sm-8">
						<?= $form->field($model, 'link')->textInput(['autofocus' => true])->label(false) ?>
					</div>
		  		</div>
		  		<div class="form-group row">
			  			<label class="col-sm-2 col-form-label">
							<div>Mô tả </div>
						</label>
						<div class="col-sm-8">
							<div class="content_footer_vi">
						  	<?= $form->field($model, 'contentVI')->textarea([
						  		'rows' => '12',
						  		'id' => 'content_footer_vi'
						  	])->label('Ngôn ngữ tiếng việt') ?>
						  	</div>
						  	<div class="content_footer_en">
						  	<?= $form->field($model, 'contentEN')->textarea([
						  		'rows' => '12',
						  		'id' => 'content_footer_en'
						  	])->label('Ngôn ngữ tiếng anh') ?>
						  	</div>
						</div>
						<!-- <div class="col-sm-8 content_footer_en" style="display: none"> -->
						<!-- </div> -->
		  		</div>
		  		<div class="form-group row">
		  			<label class="col-sm-2 col-form-label">
						Hình Ảnh
					</label>
					<div class="col-sm-10">
  						<?= $form->field($model, 'image')->fileInput(['class' => 'image', 'accept'=>".png,.jpg" ])->label(false) ?>
					  	<div class="display_image">
					  		<img src="" width=200px>
					  	</div>
					</div>
				</div>
				<div class="form-group row">
					<label  class="col-sm-2 control-label">
						Status
					</label>
					<div class="col-sm-10">
					  	<?= $form
                        ->field($model, 'status')
                        ->checkbox([
                        	"data-toggle" => "toggle", 
                        	"data-size"=>"sm",
                        	"checked"=>"checked"
                        ])->label(false)?>
					</div>
				</div>
		  		<div class="form-group row">
		  			<div class="col-sm-2"></div>
			  		<div class="col-sm-2">
					 	<button type="submit" class="btn btn-info "><i class="fa fa-plus"></i> Thêm</button>
					</div>
			  	</div>
	 		</div>
			<?php ActiveForm::end(); ?>
		</div>
	</div>
</div>

backend/views/slider/index.php
<?php
use yii\helpers\Url;
?>
<section class="content">
  <div class="row">
      <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
               <a class="btn btn-success" href="<?php echo Url::to(['/slider/add-slider']);  ?>">
                  <i class="fa fa-plus"></i> Thêm mới
               </a>
            </div>
            <div class="box-body">
                <table id="slider_backend" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                          <th>STT</th>
                          <th>Image</th>
                          <th>Status</th>                          
                          <th>Sửa</th>                          
                          <th>Xóa</th>                          
                        </tr>
                    </thead>
                    <tbody id="sortable">
                        <?php
                        $stt = 1; 
                        foreach ($slider as $sl) : ?>
                           <tr class="ui-state-default ui-sortable-handle" data-position="<?php echo $sl['positions'] ?> " data-id="<?php echo $sl['id'] ?>" data-url="slider/change-position">
                              <input type="hidden" name="id" value="<?php echo $sl['id'] ?>">
                              <td><?php echo $stt ++ ?></td>
                              <td style="width:20%">
                                 <?php if($sl['image'] == "") : ?>
                                    <div></div>
                                 <?php else : ?>   
                                    <img src="<?php echo Url::to('../'.$sl['image']); ?>" width=100px height=100px>
                                 <?php endif ?>
                              </td>
                              <td>
                             <?php if($sl['status'] == 1): ?>
                                 <input data-url="slider/change-status" data-value="<?php echo $sl['id']  ?>" name="status" class="status change-status" type="checkbox" checked data-toggle="toggle" data-size="sm" >
                              <?php else : ?>
                                 <input data-url="slider/change-status" data-value="<?php echo $sl['id'] ?>" name="status" class="status change-status" type="checkbox" data-toggle="toggle" data-size="sm">
                              <?php endif ?>
                              </td>
                              <td class="text-center">
                                <a href="<?php echo Url::to(['/slider/update-slider', 'id' => $sl['id']]);  ?>"><i class="glyphicon glyphicon-edit"></i></a>
                              </td>
                              <td class="text-center">
                                <a href="<?php echo Url::to(['/slider/delete-slider', 'id' => $sl['id']]);  ?>"> <i class="fa fa-remove"></i></a>
                              </td>
                           </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
  </div>
</section>

backend/views/slider/updateSlider.php
<?php
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
?>
<div class="box box-primary">
	<?php  echo Yii::$app->controller->renderPartial('/layouts/breadcum')  ?>
	<div class="row">
		<div class="col-md-12">
		 	<?php if (Yii::$app->session->hasFlash('success')): ?>
			    <div class="alert alert-success alert-dismissable"> 
			        <i class="icon fa fa-check"></i><?= Yii::$app->session->getFlash('success') ?>
			    </div>
			<?php endif; ?> 
			<?php if (Yii::$app->session->hasFlash('error')): ?>
			    <div class="alert alert-error alert-dismissable"> 
			        <?= Yii::$app->session->getFlash('error') ?>
			    </div>
			<?php endif; ?> 
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
    		<?php $form = ActiveForm::begin(
			[
				'id' => 'form-add-product',
				'options' => [
			        'enctype' => 'multipart/form-data'
			    ]
			]);?>
			<div class="box-body">
		  		<div class="form-group row">
		  			<?= $form->field($model, 'id')->hiddenInput(['value'=>$data['id']])->label(false); ?>
		  			<label for="name" class="col-sm-2 col-form-label">
						<div>Tên (*)</div>
						<a class="btn btn-info change" style="margin-top: 10px">Thay đổi ngôn ngữ</a>
					</label>
					<div class="col-sm-8">
							<div class="title_vi">
								<?= $form->field($model, 'nameVI')->textInput([
									'autofocus' => true,
									'value' =>  !empty(json_decode($data['name'])->vi) ? json_decode($data['name'])->vi : " "
								])->label('Ngôn ngữ tiếng việt') ?>
							</div>
							<div class="title_en">
								<?= $form->field($model, 'nameEN')->textInput([
									'autofocus' => true,
									'value' => !empty(json_decode($data['name'])->en) ? json_decode($data['name'])->en : " "
								])->label('Ngôn ngữ tiếng anh') ?>
							</div>
						</div>
		  		</div>
		  		<div class="form-group row">
		  			<label for="name" class="col-sm-2 col-form-label">
						<div>Link</div>
					</label>
					<div class="col-sm-8">
						
						<?= $form->field($model, 'link')->textInput(['value' => $data['link']])->label(false) ?>
					</div>
		  		</div>
		  		<div class="form-group row">
			  			<label class="col-sm-2 col-form-label">
							<div>Mô tả </div>
						</label>
						<div class="col-sm-8">
							<div class="content_footer_vi">
						  	<?= $form->field($model, 'contentVI')->textarea([
						  		'rows' => '12',
						  		'id' => 'content_footer_vi',
						  		'value' => !empty(json_decode($data['description'])->vi) ? json_decode($data['description'])->vi : " "
						  	])->label('Ngôn ngữ tiếng việt') ?>
						  	</div>
						  	<div class="content_footer_en">
						  	<?= $form->field($model, 'contentEN')->textarea([
						  		'rows' => '12',
						  		'id' => 'content_footer_en',
						  		'value' => !empty(json_decode($data['description'])->en) ? json_decode($data['description'])->en : " "
						  	])->label('Ngôn ngữ tiếng anh') ?>
						  	</div>
						</div>
						<!-- <div class="col-sm-8 content_footer_en" style="display: none"> -->
						<!-- </div> -->
		  		</div>
		  		<div class="form-group row">
		  			<label class="col-sm-2 col-form-label">
						Hình Ảnh
					</label>
					<div class="col-sm-10">
  						<?= $form->field($model, 'image')->fileInput([
  							'class' => 'image',
  							'accept'=>".png,.jpg",
  							'value' => Url::to([$data['image']])
  						])->label(false) ?>
					  	<div class="display_image">
					  		<?php if($data['image'] == "") : ?>
					  			<img src="" width=200px>
					  		<?php else : ?>
					  			<img src="<?php echo Url::to('../../'.$data['image'])  ?>" width=200px>
					  		<?php endif ?>
					  	</div>
					</div>
				</div>
				<div class="form-group row">
					<label  class="col-sm-2 control-label">
						Status
					</label>
					<div class="col-sm-10">
						<?php ($data['status'] == 1) ? $check = true : $check = false ?>
					  	<?= $form
                        ->field($model, 'status')
                        ->checkbox([
                        	"data-toggle" => "toggle", 
                        	"data-size"=>"sm",
                        	"checked"=>$check
                        ])->label(false)?>
					</div>
				</div>
		  		<div class="form-group row">
		  			<div class="col-sm-2"></div>
			  		<div class="col-sm-2">
					 	<button type="submit" class="btn btn-info ">Cập Nhật</button>
					</div>
			  	</div>
	 		</div>
			<?php ActiveForm::end(); ?>
		</div>
	</div>
</div>