common/models/Consultant.php
<?php
namespace common\models;
use Yii;
use yii\db\ActiveRecord;
use yii\db\Query;
use common\models\Common;
use yii\behaviors\SluggableBehavior;
class Consultant extends ActiveRecord 
{
    public static function tableName()
    {
        return '{{%consultant}}';
    }
    /**
    * Thay đổi vị trí của bài viết
    * [BACKEND INDEX] [DRAG-DROP] [JQUERY]
    **/
    public static function changePosition($position) {
        $connection = Yii::$app->db;
        foreach($position as $p) {
            $index = $p[0];
            $newPosition = $p[1];
            $connection->createCommand()
            ->update('consultant', ['positions' => $newPosition], ['id' => $index])
            ->execute();
        }
    }
    /* 
    * Thay đổi checkbox khi nhấn button
    * [BACKEND INDEX] [TOGGLE CHECKBOX] [JQUERY]
    */
    public static function changeStatus($id,$status) {
        $connection = Yii::$app->db;
        $change = $connection->createCommand()
        ->update('consultant', ['status' => $status], ['id' => $id])
        ->execute();
        if($change) {
            return true;
        }
        else {
            return false;
        }
    }
   
    /**
     * Save form post
     * @param $dataForm [dữ liệu từ form post gửi lên server]
     */
    public static function updateConsultant($dataForm) {
        if(!empty($dataForm['id'])){
            // nếu là update post
            $model = Consultant::findOne($dataForm['id']);
        }
        else{
            // nếu là thêm mới post
            $model = new Consultant();
            $model->positions = Consultant::find()->max('id') + 1;
        }
        $model->name = ! empty($dataForm['name']) ? $dataForm['name'] : "" ;
        $model->description = ! empty($dataForm['description']) ? $dataForm['description'] : "" ;
        $model->job = ! empty($dataForm['job']) ? $dataForm['job'] : "" ;
        $model->status = !empty($dataForm['status']) ? 1 : 0 ;
        if(! empty($dataForm['image'])){
            $model->image = $dataForm['image'];
        }
        return $model->save();  
    }
    /**
    * Danh sách tất cả post
    * [BACKEND INDEX] 
    **/
    public static function getAllConsultant(){
        $result = (new Query)
                ->select('id,name,description,image,status,positions,job')
                ->from(static::tableName())
                ->orderBy('positions desc,id desc')
                ->all();
        return $result;
    }
    public static function deleteConsultant($id){
        $model = Consultant::findOne($id);
        return $model->delete();
    }
    public static function getConsultant(){
        $result = (new Query)
                ->select('id,name,description,image,status,positions,job')
                ->from('consultant p')
                ->where(['p.status' => 1])
                ->orderBy('positions desc,id desc')
                ->all();
        return $result;
    }
    /**
    * Bài viết trang index
    * [FRONTEND INDEX] 
    **/
    // public static function getPost(){
    //     $result = (new Query)
    //             ->select('p.title_url,p.id,p.name,p.image,p.description,p.id_type_post,p.email,FROM_UNIXTIME(p.time_create) as `time_create`,p.short_description,tp.title_url as `tp_title_url`')
    //             ->from('post p')
    //             ->leftJoin('type_post tp', 'p.id_type_post = tp.id')
    //             ->where(['p.status' => 1])
    //             ->andWhere(['!=', 'p.id', 2]) // remove bài về chúng tôi
    //             ->orderBy('p.positions desc')
    //             ->all();
    //     return $result;
    // }
    /**
    * Chi tiết bài viết
    * [FRONTEND DETAIL-POST] 
    **/
    // public static function getPostId($id) {
    //     $result = (new Query)
    //         ->select('tp.title_url,p.description,p.name,tp.id as tp_id,tp.name as tp_name')
    //         ->from('post p')
    //         ->leftJoin('type_post tp', 'p.id_type_post = tp.id')
    //         ->where(['p.status' => 1,'p.title_url' => $id])
    //         ->one();
    //     return $result;
    // }
    /**
    * Danh sách bài post liên quan
    * [FRONTEND DETAIL-POST] 
    **/
    // public static function relatePost ($id,$idTypePost) {
    //     $result = (new Query)
    //             ->select('p.name,p.description,p.id_type_post,p.id,p.title_url,tp.title_url as `tp_title_url`')
    //             ->from('post p')
    //             ->leftJoin('type_post tp', 'p.id_type_post = tp.id')
    //             ->where(['p.status' => '1','p.id_type_post' => $idTypePost])
    //             ->andWhere(['not in','p.title_url',[$id]])
    //             ->limit('4')
    //             ->orderBy('p.positions desc')
    //             ->all();
    //     return $result;
    // }
}

backend/controllers/ConsultantController.php
<?php
namespace backend\controllers;
use Yii;
use yii\web\Controller;
use yii\web\UploadedFile;
use common\models\forms\ConsultantForm;
use common\models\Consultant;
use common\models\TypePost;
use yii\helpers\ArrayHelper;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\BaseInflector;
use yii\helpers\StringHelper;
use yii\widgets\ActiveForm;
use yii\web\Response;
/**
 * Post controller
 */
class ConsultantController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [ 'index','add-consultant','update-consultant','delete-consultant','change-status','change-position'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }
    /**
     * {@inheritdoc}
     */
    public $enableCsrfValidation = false; // use method post
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    /**
     * render dữ liệu vào View [Index]
     */
    public function actionIndex(){
        $allData = Consultant::getAllConsultant(); // lấy tất cả slider
        return $this->render('index',
            [
                'allData' => $allData,
            ]
        );
    }
    public function actionAddConsultant(){
        Yii::$app->view->title = "Thêm bài viết";
        $model = new ConsultantForm();
        // $allData = Consultant::getAllConsultant(); 
        
        if($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->image = UploadedFile::getInstance($model, 'image');
            $dataForm = Yii::$app->request->post()['ConsultantForm'];
            // print_r($dataForm);
            // die();
            if(! empty($model->image->name)) { // nếu upload hình ảnh thành công
                $link = $model->upload(); // lưu vào path
                if($link){ // nếu có link trả về
                    $dataForm['image'] = $link; // gán biến dataForm logo vào Form
                }        
            }
           
           
            
            // $dataForm  
            $dataForm['job'] = json_encode(array('vi' => $dataForm['jobVI'],'en' => $dataForm['jobEN'])) ;
            $dataForm['description'] = json_encode(array('vi' => $dataForm['contentVI'],'en' => $dataForm['contentEN'])) ;
            
            $saveSetting = Consultant::updateConsultant($dataForm); // save form
            if($saveSetting) { // nếu save setting thành công  
                Yii::$app->session->setFlash('success', "Thêm thành công");
                return $this->redirect(['/consultant']);
            }
            else {
                Yii::$app->session->setFlash('error', "Thêm không thành công");
                return $this->redirect(['/consultant']);
            }  
        }     
        // print_r($map);
        // die();
        return $this->render('addConsultant',
            [
                'model' => $model,
                // 'map' => $map,
                // 'position' => $position,
            ]
        );
    }
    /**
     * render dữ liệu vào View [updateTypePost]
     */
    public function actionUpdateConsultant(){
        Yii::$app->view->title = "Update bài viết";
        $id = Yii::$app->request->get('id'); // lấy dữ liệu từ URL
        $model = new ConsultantForm();
        $data = Consultant::findOne($id); // Lấy dữ liệu từ db theo Id
        if($data){ // Nếu có dữ liệu
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                $model->image = UploadedFile::getInstance($model, 'image');
                $dataForm = Yii::$app->request->post()['ConsultantForm'];
                // print_r($dataForm);
                // die();
                if(! empty($model->image->name)) { // nếu upload hình ảnh thành công
                    $link = $model->upload(); // lưu vào path
                    if($link){ // nếu có link trả về
                        $dataForm['image'] = $link; // gán biến dataForm logo vào Form
                    }        
                }
               
               
                
                // $dataForm  
                $dataForm['job'] = json_encode(array('vi' => $dataForm['jobVI'],'en' => $dataForm['jobEN'])) ;
                $dataForm['description'] = json_encode(array('vi' => $dataForm['contentVI'],'en' => $dataForm['contentEN'])) ;
                $saveSetting = Consultant::updateConsultant($dataForm); // save form
                if($saveSetting) { // nếu save setting thành công  
                    Yii::$app->session->setFlash('success', "Update thành công");
                    return $this->redirect(['/consultant/update-consultant','id' => $id]);
                }
                else {
                    Yii::$app->session->setFlash('error', "Update không thành công");
                    return $this->redirect(['/consultant/update-consultant','id' => $id]);
                }  
            }    
            return $this->render('updateConsultant',
                [
                    'model' => $model,
                    'data' => $data,
                    // 'map' => $map,
                    // 'position' => $position
                ]
            );
        }
        else { // Nếu không có dữ liệu
            Yii::$app->session->setFlash('error', "Không có dữ liệu");
            return $this->redirect(['/Post']);
        }
    }
    public function actionDeleteConsultant() {
        $id = Yii::$app->request->get('id');
        $delete = Consultant::deleteConsultant($id);
        return $this->redirect(['/consultant']);
    }
    public function actionChangeStatus() {
        $id = Yii::$app->request->get('id');
        $value = Yii::$app->request->get('value');
        $change = Consultant::changeStatus($id,$value);
        if($change) {
            return true;
        } 
        else {
            return false;
        }
    }
    public function actionChangePosition() {
        $positions = Yii::$app->request->get('positions');
        $change = Consultant::changePosition($positions);
        return true;
    }
}
   

backend/views/consultant/addConsultant.php
<?php
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
?>
<div class="box box-primary">
	<?php  echo Yii::$app->controller->renderPartial('/layouts/breadcum')  ?>
	<div class="row">
		<div class="col-md-12">
		 	<?php if (Yii::$app->session->hasFlash('success')): ?>
			    <div class="alert alert-success alert-dismissable"> 
			        <i class="icon fa fa-check"></i><?= Yii::$app->session->getFlash('success') ?>
			    </div>
			<?php endif; ?> 
			<?php if (Yii::$app->session->hasFlash('error')): ?>
			    <div class="alert alert-error alert-dismissable"> 
			        <?= Yii::$app->session->getFlash('error') ?>
			    </div>
			<?php endif; ?> 
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
    		<?php $form = ActiveForm::begin(
			[
				// 'enableAjaxValidation' => true,
				'id' => 'form-add-product',
				'options' => [
			        'enctype' => 'multipart/form-data'
			    ]
			]);?>
			<div class="box-body">
		  		<div class="form-group row">
		  			<label for="name" class="col-sm-2 col-form-label">
						<div>Tên (*)</div>
						<a class="btn btn-info change" style="margin-top: 10px">Thay đổi ngôn ngữ</a>
					</label>
					<div class="col-sm-8">
							
						<?= $form->field($model, 'name')->textInput(['autofocus' => true])->label(false) ?>
							
					</div>
		  		</div>
		  		<div class="form-group row">
		  			<label for="name" class="col-sm-2 col-form-label">
						<div>Chức vụ</div>
					</label>
					<div class="col-sm-8">
							<div class="title_vi">
								<?= $form->field($model, 'jobVI')->textInput(['autofocus' => true])->label('Ngôn ngữ tiếng việt') ?>
							</div>
							<div class="title_en">
								<?= $form->field($model, 'jobEN')->textInput(['autofocus' => true])->label('Ngôn ngữ tiếng anh') ?>
							</div>
						</div>
		  		</div>
		  		
		  		<div class="form-group row">
			  			<label class="col-sm-2 col-form-label">
							<div>Mô tả </div>
						</label>
						<div class="col-sm-8">
							<div class="content_footer_vi">
						  	<?= $form->field($model, 'contentVI')->textarea([
						  		'rows' => '12',
						  		'id' => 'content_footer_vi'
						  	])->label('Ngôn ngữ tiếng việt') ?>
						  	</div>
						  	<div class="content_footer_en">
						  	<?= $form->field($model, 'contentEN')->textarea([
						  		'rows' => '12',
						  		'id' => 'content_footer_en'
						  	])->label('Ngôn ngữ tiếng anh') ?>
						  	</div>
						</div>
		  		</div>
		  		
				
		  		<div class="form-group row">
		  			<label class="col-sm-2 col-form-label">
						Hình Ảnh
					</label>
					<div class="col-sm-10">
  						<?= $form->field($model, 'image')->fileInput(['class' => 'image', 'accept'=>".png,.jpg" ])->label(false) ?>
					  	<div class="display_image">
					  		<img src="" width=200px>
					  	</div>
					  	<div>Hình Ảnh (370x240)</div>
					</div>
				</div>
				<div class="form-group row">
					<label  class="col-sm-2 control-label">
						Status
					</label>
					<div class="col-sm-10">
					  	<?= $form
                        ->field($model, 'status')
                        ->checkbox([
                        	"data-toggle" => "toggle", 
                        	"data-size"=>"sm",
                        	"checked"=>"checked"
                        ])->label(false)?>
					</div>
				</div>
		  		<div class="form-group row">
		  			<div class="col-sm-2"></div>
			  		<div class="col-sm-2">
					 	<button type="submit" class="btn btn-info "><i class="fa fa-plus"></i> Thêm</button>
					</div>
			  	</div>
	 		</div>
			<?php ActiveForm::end(); ?>
		</div>
	</div>
</div>

backend/views/consultant/index.php
<?php
use yii\helpers\Url;
use yii\jui\Sortable;
?>
<style>
  ul{padding-left:0px;}
  .padding{
    padding:10px;
  }
</style>
<section class="content">
  <div class="row">
      <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
               <a class="btn btn-success" href="<?php echo Url::to(['/consultant/add-consultant']);  ?>">
                  <i class="fa fa-plus"></i> Thêm mới
               </a>
            </div>
            <div class="box-body">
                <table id="slider_backend" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                          <th>STT</th>
                          <th>Tên</th>
                          <!-- <th>Description</th> -->
                          <th>Image</th>
                          <th>Status</th>                          
                          <th>Sửa</th>                          
                          <th>Xóa</th>                          
                        </tr>
                    </thead>
                    <tbody id="sortable">
                        <?php
                        $stt = 1; 
                        foreach ($allData as $ad) : ?>
                           <tr class="ui-state-default ui-sortable-handle" data-position="<?php echo $ad['positions'] ?> " data-id="<?php echo $ad['id'] ?>" data-url="consultant/change-position" >
                              <input type="hidden" name="id" value="<?php echo $ad['id'] ?>">
                              <td><?php echo $stt ++ ?></td>
                              <td style="text-align: left;padding:0px">
                                  <div class="padding"><?php echo $ad['name'] ?></div>
                              </td>
                              <td style="width:20%">
                                 <?php if($ad['image'] == "") : ?>
                                    <div></div>
                                 <?php else : ?>   
                                    <img src="<?php echo Url::to('../'.$ad['image']); ?>" width=100px height=100px>
                                 <?php endif ?>
                              </td>
                              <td>
                              <?php if($ad['status'] == 1): ?>
                                 <input data-url="consultant/change-status" data-value="<?php echo $ad['id']  ?>" name="status" class="status change-status" type="checkbox" checked data-toggle="toggle" data-size="sm" >
                              <?php else : ?>
                                 <input data-url="consultant/change-status" data-value="<?php echo $ad['id'] ?>" name="status" class="status change-status" type="checkbox" data-toggle="toggle" data-size="sm">
                              <?php endif ?>
                              </td>
                              <td class="text-center">
                                <a href="<?php echo Url::to(['/consultant/update-consultant', 'id' => $ad['id']]);  ?>"><i class="glyphicon glyphicon-edit"></i></a>
                              </td>
                              <td class="text-center">
                                
                                <a href="<?php echo Url::to(['/consultant/delete-consultant', 'id' => $ad['id']]);  ?>"> <i class="fa fa-remove"></i></a>
                              
                              </td>
                           </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
  </div>
</section>

backend/views/consultant/updateConsultant.php
<?php
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
?>
<div class="box box-primary">
	<?php  echo Yii::$app->controller->renderPartial('/layouts/breadcum')  ?>
	<div class="row">
		<div class="col-md-12">
		 	<?php if (Yii::$app->session->hasFlash('success')): ?>
			    <div class="alert alert-success alert-dismissable"> 
			        <i class="icon fa fa-check"></i><?= Yii::$app->session->getFlash('success') ?>
			    </div>
			<?php endif; ?> 
			<?php if (Yii::$app->session->hasFlash('error')): ?>
			    <div class="alert alert-error alert-dismissable"> 
			        <?= Yii::$app->session->getFlash('error') ?>
			    </div>
			<?php endif; ?> 
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
    		<?php $form = ActiveForm::begin(
			[
				// 'enableAjaxValidation' => true,
				'id' => 'form-add-product',
				'options' => [
			        'enctype' => 'multipart/form-data'
			    ]
			]);?>
			<div class="box-body">
		  		<div class="form-group row">
		  			<?= $form->field($model, 'id')->hiddenInput(['value'=>$data['id']])->label(false); ?>
		  			<label for="name" class="col-sm-2 col-form-label">
						<div>Tên (*)</div>
						<a class="btn btn-info change" style="margin-top: 10px">Thay đổi ngôn ngữ</a>
					</label>
					<div class="col-sm-8">
						
							<?= $form->field($model, 'name')->textInput([
								'autofocus' => true,
								'value' =>  $data['name']
							])->label(false) ?>
						
						
					</div>
		  		</div>
		  		<div class="form-group row">
		  			
		  			<label for="name" class="col-sm-2 col-form-label">
						<div>Chức Vụ</div>
						
					</label>
					<div class="col-sm-8">
						<div class="title_vi">
							<?= $form->field($model, 'jobVI')->textInput([
								'autofocus' => true,
								'value' =>  !empty(json_decode($data['job'])->vi) ? json_decode($data['job'])->vi : " "
							])->label('Ngôn ngữ tiếng việt') ?>
						</div>
						<div class="title_en">
							<?= $form->field($model, 'jobEN')->textInput([
								'autofocus' => true,
								'value' => !empty(json_decode($data['job'])->en) ? json_decode($data['job'])->en : " "
							])->label('Ngôn ngữ tiếng anh') ?>
						</div>
					</div>
		  		</div>
		  		<div class="form-group row">
		  			<label class="col-sm-2 col-form-label">
						<div>Mô tả </div>
					</label>
					<div class="col-sm-8">
						<div class="content_footer_vi">
					  	<?= $form->field($model, 'contentVI')->textarea([
					  		'rows' => '12',
					  		'id' => 'content_footer_vi',
					  		'value' => !empty(json_decode($data['description'])->vi) ? json_decode($data['description'])->vi : " "
					  	])->label('Ngôn ngữ tiếng việt') ?>
					  	</div>
					  	<div class="content_footer_en">
					  	<?= $form->field($model, 'contentEN')->textarea([
					  		'rows' => '12',
					  		'id' => 'content_footer_en',
					  		'value' => !empty(json_decode($data['description'])->en) ? json_decode($data['description'])->en : " "
					  	])->label('Ngôn ngữ tiếng anh') ?>
					  	</div>
					</div>
		  		</div>
		  		
				
		  		<div class="form-group row">
		  			<label class="col-sm-2 col-form-label">
						Hình Ảnh
					</label>
					<div class="col-sm-10">
  						<?= $form->field($model, 'image')->fileInput([
  							'class' => 'image',
  							'accept'=>".png,.jpg",
  							'value' => Url::to([$data['image']])
  						])->label(false) ?>
					  	<div class="display_image">
					  		<img src="<?php echo Url::to('../../'.$data['image']); ?>" width=200px>
					  	</div>
					  	<div>Hình Ảnh (370x240)</div>
					</div>
				</div>
				<div class="form-group row">
					<label  class="col-sm-2 control-label">
						Status
					</label>
					<div class="col-sm-10">
						<?php ($data['status'] == 1) ? $check = true : $check = false ?>
					  	<?= $form
                        ->field($model, 'status')
                        ->checkbox([
                        	"data-toggle" => "toggle", 
                        	"data-size"=>"sm",
                        	'checked' => $check,
                        ])->label(false)?>
					</div>
				</div>
		  		<div class="form-group row">
		  			<div class="col-sm-2"></div>
			  		<div class="col-sm-2">
					 	<button type="submit" class="btn btn-info ">Cập Nhật</button>
					</div>
			  	</div>
	 		</div>
			<?php ActiveForm::end(); ?>
		</div>
	</div>
</div>